### ISSUE TITLE
Hackuje z HS3 🦙

### ISSUE THREAD

**Issue by KGrzeg** [hs3city/hacktoberfest#25]

**Comment by kinga-marszalkowska** [comment]
Cześć 👋 Masz 4 pull requesty? Jeśli tak, wklej screena profilu! 😊

**Comment by KGrzeg** [comment]
![image](https://user-images.githubusercontent.com/27036554/140832351-ff72bbd6-55db-44cb-a18e-690c5fbe84d5.png)

DigitalOcean jeszcze tego nie wie, ale zadanie wykonane :)
